BookStoreWeb/Areas/Admin/Controllers/AuthorController.cs
using BookStore.DataAccess.Repository.IRepository;
using BookStore.Models.DomainModels.DbModels;
using Microsoft.AspNetCore.Mvc;

namespace BookStoreWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AuthorController : Controller
    {
        private readonly IUnitOfWork _dbContext;

        public AuthorController(IUnitOfWork dbContext)
        {
            _dbContext = dbContext;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> Upsert(int? id)
        {
            Author author = new();
            if (id == null || id == 0)
            {
                // create product
                return View(author);
            }
            else
            {
                author = await _dbContext.Authors.GetFirstOrDefault(u => u.Id == id);
                return View(author);

            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(Author author)
        {
            try
            {
                if (ModelState.IsValid)
                {                   
                    if (author.Id == 0)
                    {
                        await _dbContext.Authors.Add(author);
                    }
                    else
                    {
                        await _dbContext.Authors.Update(author);
                    }
                    await _dbContext.SaveAsync();
                    TempData["success"] = "Author created successfully";
                    return RedirectToAction("Index");
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        #region API Endpoints
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var authors = await _dbContext.Authors.GetAll();
            return Json(new { data = authors });
        }

        //POST
        [HttpDelete]
        public async Task<IActionResult> Delete(int? id)
        {
            var authorToDelete = await _dbContext.Authors.GetFirstOrDefault(u => u.Id == id);
            if (authorToDelete == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            await _dbContext.Authors.Remove(authorToDelete);
            await _dbContext.SaveAsync();
            return Json(new { success = true, message = "Delete Successful" });

        }
        #endregion

    }
}

BookStoreWeb/Areas/Admin/Controllers/CompanyController.cs
using BookStore.DataAccess.Repository.IRepository;
using BookStore.Models.DomainModels.DbModels;
using Microsoft.AspNetCore.Mvc;

namespace BookStoreWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _dbContext;

        public CompanyController(IUnitOfWork dbContext)
        {
            _dbContext = dbContext;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> Upsert(int? id)
        {
            Company company = new();
            if (id == null || id == 0)
            {
                // create product
                return View(company);
            }
            else
            {
                company = await _dbContext.Companies.GetFirstOrDefault(u => u.Id == id);
                return View(company);

            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(Company company)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (company.Id == 0)
                    {
                        await _dbContext.Companies.Add(company);
                    }
                    else
                    {
                        await _dbContext.Companies.Update(company);
                    }
                    await _dbContext.SaveAsync();
                    TempData["success"] = "Company created successfully";
                    return RedirectToAction("Index");
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        #region API Endpoints
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var companies = await _dbContext.Companies.GetAll();
            return Json(new { data = companies });
        }

        //POST
        [HttpDelete]
        public async Task<IActionResult> Delete(int? id)
        {
            var companyToDelete = await _dbContext.Companies.GetFirstOrDefault(u => u.Id == id);
            if (companyToDelete == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            await _dbContext.Companies.Remove(companyToDelete);
            await _dbContext.SaveAsync();
            return Json(new { success = true, message = "Delete Successful" });

        }
        #endregion

    }
}

BookStoreWeb/Areas/Admin/Controllers/ProductController.cs
using BookStore.DataAccess.Repository.IRepository;
using BookStore.Models.DomainModels.DbModels;
using BookStore.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace BookStoreWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _dbContext;
        private readonly IWebHostEnvironment _hostEnvironment;

        public ProductController(IUnitOfWork dbContext, IWebHostEnvironment hostEnvironment)
        {
            _dbContext = dbContext;
            _hostEnvironment = hostEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            ProductViewModel productView = new()
            {
                Product = new(),
                CategoryList = (await _dbContext.Categories.GetAll()).Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                }),
                CoverTypeList = (await _dbContext.BookCovers.GetAll()).Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                }),
                AuthorList = (await _dbContext.Authors.GetAll()).Select(x => new SelectListItem
                {
                    Text = x.FullName,
                    Value = x.Id.ToString()
                })
            };
            if (id == null || id == 0)
            {
                // create product
                return View(productView);
            }
            else
            {
                productView.Product = await _dbContext.Products.GetFirstOrDefault(u => u.Id == id);
                return View(productView);

            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(ProductViewModel productView, IFormFile? file)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string wwwRootPath = _hostEnvironment.WebRootPath;
                    if (file != null)
                    {
                        string fileName = Guid.NewGuid().ToString();
                        var uploads = Path.Combine(wwwRootPath, @"images\products");
                        var extension = Path.GetExtension(file.FileName);

                        if (productView.Product.ImageUrl != null)
                        {
                            // if imga is update remove old image
                            var oldImagePath = Path.Combine(wwwRootPath, productView.Product.ImageUrl.TrimStart('\\'));
                            if (System.IO.File.Exists(oldImagePath))
                            {
                                System.IO.File.Delete(oldImagePath);
                            }
                        }

                        using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                        {
                            file.CopyTo(fileStreams);
                        }
                        productView.Product.ImageUrl = @"\images\products\" + fileName + extension;

                    }
                    if (productView.Product.Id == 0)
                    {
                       await _dbContext.Products.Add(productView.Product);
                    }
                    else
                    {
                       await _dbContext.Products.Update(productView.Product);
                    }
                    await _dbContext.SaveAsync();
                    TempData["success"] = "Product created successfully";
                    return RedirectToAction("Index");
                }
                return View(productView);
            }
            catch
            {
                return View();
            }
        }

        #region API Endpoints
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var productList = await _dbContext.Products.GetAll(includes:x => x.Include(x => x.CoverType).Include(x => x.Category).Include(x => x.Author));
            return Json(new { data = productList });
        }

        //POST
        [HttpDelete]
        public async Task<IActionResult> Delete(int? id)
        {
            var obj = await _dbContext.Products.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }

            await _dbContext.Products.Remove(obj);
            await _dbContext.SaveAsync();
            return Json(new { success = true, message = "Delete Successful" });

        }
        #endregion

    }
}

BookStoreWeb/Controllers/CategoryController.cs
using BookStore.DataAccess.Data;
using BookStore.DataAccess.Repository.IRepository;
using BookStore.Models.DomainModels.DbModels;
using Microsoft.AspNetCore.Mvc;

namespace BookStoreWeb.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _dbContext;

        public CategoryController(IUnitOfWork dbContext)
        {
            _dbContext = dbContext;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Category> categoryList = await _dbContext.Categories.GetAll();
            return View(categoryList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Category category)
        {
            if (category.Name == category.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Name", "The Displayorder cannot exactly match the Name.");
                return View(category);
            }
            if (ModelState.IsValid)
            {
                await _dbContext.Categories.Add(category);
                await _dbContext.SaveAsync();
                TempData["success"] = "Category created successfully";
                return RedirectToAction("Index");
            }
            return View(category);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return BadRequest();
            }
            var category = await _dbContext.Categories.GetFirstOrDefault(x => x.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Category categoryToEdit)
        {
            if (categoryToEdit.Name == categoryToEdit.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Name", "The Displayorder cannot exactly match the Name.");
            }
            if (ModelState.IsValid)
            {
               await  _dbContext.Categories.Update(categoryToEdit);
                await _dbContext.SaveAsync();
                TempData["success"] = "Category edit successfully";
                return RedirectToAction("Index");
            }
            return View(categoryToEdit);
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return BadRequest();
            }
            var categoryToDelete = await _dbContext.Categories.GetFirstOrDefault(x => x.Id == id);
            if (categoryToDelete == null)
            {
                return NotFound();
            }

            return View(categoryToDelete);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Category categoryToDelete)
        {
            await _dbContext.Categories.Remove(categoryToDelete);

            await _dbContext.SaveAsync();
            TempData["success"] = "Category removed successfully";
            return RedirectToAction("Index");
        }
    }
}

BookStoreWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStoreWeb</title>
    @*    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css" />

    @* <link rel="stylesheet" href="~/BookStoreWeb.styles.css" asp-append-version="true" />*@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">BookStoreWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Admin Panel</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category Index</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="CoverType" asp-action="Index">Cover Type Index</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Author" asp-action="Index">Author Index</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company Index</a>
                                 <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product Index</a>
                                <div class="dropdown-divider"></div>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="Customer" asp-controller="ShoppingCart" asp-action="Index"><i class="bi bi-cart3"></i></a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                    <form class="d-flex" wtx-context="AAFF816F-D9DF-411B-8547-EA1463319592">
                        <input class="form-control me-sm-2" type="text" placeholder="Search" wtx-context="8DC5C17D-DBF4-4179-9458-1124AC484D1D">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary">
        <div class="container">
            &copy; 2022 - BookStoreWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	  <script src="https://cdn.tiny.cloud/1/72y1i886f7g5m56ij4oxrhv8g932gz9rq2a6i2rinlonrk1t/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookStoreWeb/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')    
    </script>
}
@if(TempData["error"] != null)
{
     <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
     <script type="text/javascript">
        toastr.success('@TempData["error"]')    
    </script>
}