BookStoreWeb/Areas/Admin/Controllers/CoverTypeController.cs
using BookStore.DataAccess.Repository.IRepository;
using BookStore.Models.DomainModels.DbModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BookStoreWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CoverTypeController : Controller
    {
        private readonly IUnitOfWork _dbContext;

        public CoverTypeController(IUnitOfWork dbContext)
        {
            _dbContext = dbContext;
        }
        public async Task<IActionResult> Index()
        {
            var coverTypes = await _dbContext.BookCovers.GetAll();
            return View(coverTypes);
        }



        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CoverType coverType)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _dbContext.BookCovers.Add(coverType);
                    await _dbContext.SaveAsync();
                    TempData["success"] = "CoverType created successfully";
                    return RedirectToAction(nameof(Index));
                }
                return View(coverType);
            }
            catch
            {
                return View(coverType);
            }
        }


        public async Task<IActionResult> Edit(int id)
        {
            if (id == null || id == 0)
            {
                return BadRequest();
            }
            var coverType = await _dbContext.BookCovers.GetFirstOrDefault(x => x.Id == id);
            if (coverType == null)
            {
                return NotFound();
            }

            return View(coverType);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CoverType cover)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _dbContext.BookCovers.Update(cover);
                    await _dbContext.SaveAsync();
                    TempData["success"] = "Cover Type edit successfully";
                    return RedirectToAction(nameof(Index));
                }
                return View(cover);
            }
            catch
            {
                return View();
            }
        }


        public async Task<IActionResult> Delete(int id)
        {
            if (id == null || id == 0)
            {
                return BadRequest();
            }
            var coverToDelete = await _dbContext.BookCovers.GetFirstOrDefault(x => x.Id == id);
            if (coverToDelete == null)
            {
                return NotFound();
            }

            return View(coverToDelete);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(CoverType coverToDelete)
        {
            try
            {
                await _dbContext.BookCovers.Remove(coverToDelete);

                await _dbContext.SaveAsync();
                TempData["success"] = "Book Cover removed successfully";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

BookStoreWeb/Areas/Admin/Views/CoverType/Create.cshtml
@model CoverType
<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Cover Type</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3 form-group">
            <label class="form-label" asp-for="Name"></label>
            <input class="form-control" asp-for="Name" value="" />
            <span asp-validation-for=@Model.Name class="text-danger"></span>
        </div>       
        <button type="submit" class="btn btn-primary">
            Create
        </button>
        <a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary">Back to list</a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BookStoreWeb/Areas/Admin/Views/CoverType/Delete.cshtml
@model BookStore.Models.DomainModels.DbModels.CoverType

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cover Type</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BookStoreWeb/Areas/Admin/Views/CoverType/Edit.cshtml
@model CoverType
@{
    ViewData["Title"] = "Edit";
}
<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Cover Type</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <input type="hidden" asp-for=@Model.Id />
        <div class="mb-3 form-group">
            <label class="form-label" asp-for=@Model.Name></label>
            <input class="form-control" asp-for=@Model.Name/>
            <span asp-validation-for=@Model.Name class="text-danger"></span>
        </div>     
        <button type="submit" class="btn btn-primary">
            Update
        </button>
        <a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary">Back to list</a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BookStoreWeb/Areas/Admin/Views/CoverType/Index.cshtml
@model IEnumerable<BookStore.Models.DomainModels.DbModels.CoverType>

@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Cover Type List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="CoverType" asp-action="Create" class="btn btn-primary"><i class="bi bi-plus-circle me-1"></i>Create New Cover</a>
        </div>
    </div>
    <br /><br />
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="w-50">
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        <div class="btn-group w-100" role="group">
                            <a class="me-1 btn btn-warning" asp-controller="CoverType" asp-action="Edit" asp-route-id=@item.Id> <i class="bi bi-pencil-square me-1"></i>Edit</a>
                            <a class="me-1 btn btn-danger" asp-controller="CoverType" asp-action="Delete" asp-route-id=@item.Id> <i class="bi bi-trash me-1"></i>Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>